#!/usr/bin/env bash
set -euo pipefail

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
chapter="$repo_root/report/02-requirements-and-software-solution-design/2.4-requirements-specification"
stories="$chapter/2.4.1-user-stories.md"
backlog="$chapter/2.4.3-product-backlog.md"
candidate_contexts="$repo_root/report/02-requirements-and-software-solution-design/2.5-strategic-level-domain-driven-design/2.5.1-eventstorming/2.5.1.1-candidate-context-discovery.md"

required_files=(
  "$repo_root/report/00-front-matter/00-cover.md"
  "$repo_root/report/00-front-matter/03-contents.md"
  "$repo_root/report/00-front-matter/04-student-outcome.md"
  "$repo_root/report/01-presentation/1.3-target-segments/target-segments.md"
  "$repo_root/report/02-requirements-and-software-solution-design/2.2-interviews/2.2.3-interview-analysis.md"
  "$candidate_contexts"
  "$repo_root/report/02-requirements-and-software-solution-design/2.6-tactical-level-domain-driven-design/2.6.1-bounded-context-coverage.md"
  "$repo_root/report/03-solution-ui-ux-design/chapter-overview.md"
  "$repo_root/report/04-product-implementation-and-validation/chapter-overview.md"
  "$repo_root/report/04-product-implementation-and-validation/4.2-landing-page-services-and-applications-implementation/4.2.1-sprints/section-overview.md"
  "$repo_root/delivery-checklists/mobile-v1-story-verification-register.md"
  "$chapter/2.4.1-user-stories.md"
  "$chapter/2.4.2-impact-mapping.md"
  "$chapter/2.4.3-product-backlog.md"
  "$repo_root/report/93-annexes/annex-d-spike-story/spike-story.md"
)

for file in "${required_files[@]}"; do
  [[ -f "$file" ]] || { echo "missing required report artifact: $file" >&2; exit 1; }
done

bash "$repo_root/scripts/check-report-links.sh"
python3 "$repo_root/scripts/verify-mobile-v1-transcription.py"
python3 "$repo_root/scripts/verify-mobile-v1-review-register.py"
python3 "$repo_root/scripts/verify-bibliography-citations.py"
python3 "$repo_root/scripts/verify-mobile-v1-semantics.py"
python3 "$repo_root/scripts/verify-chapter-2.5.py"
python3 "$repo_root/scripts/verify-mobile-backlog.py"
python3 "$repo_root/scripts/verify-mobile-v1-rubric-template.py"

headings=$(rg -c '^##### MOB-US-' "$stories")
functional_index_rows=$(awk -F'|' '/^\| [0-9]+ \| MOB-US-/{c++} END{print c+0}' "$stories")
scenarios=$(rg -o '\*\*Scenario:' "$stories" | wc -l | tr -d ' ')
context_rows=$(awk -F'|' '/^\| BC-[0-9][0-9] \|/{c++} END{print c+0}' "$candidate_contexts")
sprint_rows=$(awk -F'|' '/^## Sprints planificados/{in_section=1; next} in_section && /^\| S[1-4] \|/{c++} END{print c+0}' "$backlog")

[[ "$headings" -eq 73 ]] || { echo "expected 73 functional story headings, got $headings" >&2; exit 1; }
[[ "$functional_index_rows" -eq 73 ]] || { echo "expected 73 functional index rows, got $functional_index_rows" >&2; exit 1; }
[[ "$scenarios" -ge 140 ]] || { echo "expected meaningful Gherkin coverage, got $scenarios scenarios" >&2; exit 1; }
[[ "$context_rows" -eq 11 ]] || { echo "expected 11 strategic Bounded Context rows, got $context_rows" >&2; exit 1; }
[[ "$sprint_rows" -eq 4 ]] || { echo "expected S1/S2/S3/S4 rows, got $sprint_rows" >&2; exit 1; }

if rg -n -i '\b(AI-generated|generated by AI|Codex|LLM|subagent|agentic|prompt engineering)\b' \
  "$repo_root/README.md" "$chapter" "$repo_root/report/93-annexes/annex-d-spike-story" --glob '*.md'; then
  echo "prohibited internal attribution found in Chapter 2.4 documentation" >&2
  exit 1
fi

if rg -n '[[:blank:]]+$' "$chapter" "$repo_root/report/93-annexes/annex-d-spike-story" --glob '*.md'; then
  echo "trailing whitespace found in Chapter 2.4 documentation" >&2
  exit 1
fi

echo "report structure OK: functional_stories=$headings index_rows=$functional_index_rows scenarios=$scenarios bounded_contexts=$context_rows backlog_sprints=$sprint_rows"
